Adding gallazzi data
SWIFTSIM/velociraptor-comparison-data pull request #103
Opened 2021-11-12 14:38 UTC by correac

Adding a stellar mass-[alpha/Fe] relation taken from Gallazzi+ (2021) (https://ui.adsabs.harvard.edu/abs/2021MNRAS.502.4457G/abstract)

2021-11-15 13:03 UTC, bwvdnbro requested changes

2021-11-15 13:03 UTC, bwvdnbro commented on data/GalaxyStellarMassAlphatoIron/conversion/convertGallazzi2021.py
> +input_filename = "../raw/Gallazzi_2021_ascii.txt"
```suggestion
input_filename = "../raw/gallazzi_2021_ascii.txt"
```
As also revealed by the automatic testing: the name used here is not the same as the name of the actual file.

2021-11-23 11:23 UTC, EvgeniiChaikin requested changes
Hi @correac 

Thank you for adding this nice dataset!

I've had a look at your changes and added a few comments to your script.  There is one comment about the hubble parameter `h` - I am thinking that in the current version we may have two extra `h` in `Mstar` but I might also be wrong.

2021-11-23 11:23 UTC, EvgeniiChaikin commented on data/GalaxyStellarMassAlphatoIron/conversion/convertGallazzi2021.py
> +    "The metallicity is expressed as [alpha/Fe]. "
Please indicate that alpha stands for Oxygen

2021-11-23 11:23 UTC, EvgeniiChaikin commented on data/GalaxyStellarMassAlphatoIron/conversion/convertGallazzi2021.py
> +M_star = 10 ** raw[:, 0] * unyt.Solar_Mass * (h_sim / h_obs) ** -2
If I am reading it correctly,` Mstar `will have the units of **Msun h^-2** but you are telling `unyt` that the units of `Mstar` are just `Msun` (that is, without `h**2`)

Are you sure this is the correct way?

2021-11-23 11:23 UTC, EvgeniiChaikin commented on data/GalaxyStellarMassAlphatoIron/conversion/convertGallazzi2021.py
> +    Z_median, scatter=y_scatter, comoving=True, description="Stellar metallicity"
Stellar metallicity -> [alpha/Fe]*

2021-11-23 11:27 UTC, EvgeniiChaikin commented on data/GalaxyStellarMassAlphatoIron/raw/gallazzi_2021_ascii.txt
> +# mass-metallicity data from Gallazzi et al. 2021
Could you please indicate which table or equation in the paper these data (numbers) come from?

2021-11-23 11:29 UTC, EvgeniiChaikin commented
In the current version, the Gallazzi+ (2021) data looks like this

![stellar_mass_star_o_over_fe_100](https://user-images.githubusercontent.com/20153933/143016447-d66f6edc-8039-415f-93f5-099ac889212d.png)

Are the errors of the expected size?

2021-11-29 09:31 UTC, correac commented on data/GalaxyStellarMassAlphatoIron/raw/gallazzi_2021_ascii.txt
> +# mass-metallicity data from Gallazzi et al. 2021
These numbers come from bottom panel of Fig. 4.

2021-11-29 09:31 UTC, correac commented on data/GalaxyStellarMassAlphatoIron/conversion/convertGallazzi2021.py
> +    Z_median, scatter=y_scatter, comoving=True, description="Stellar metallicity"
Correct!

2021-11-29 09:31 UTC, correac commented on data/GalaxyStellarMassAlphatoIron/conversion/convertGallazzi2021.py
> +    "The metallicity is expressed as [alpha/Fe]. "
Alpha does not stand for Oxygen. Gallazi et al. adopt a semi-empirical estimate of [𝛼/Fe] building on the work of Gallazzi et al. (2006). For each galaxy they measure the index ratio Mgb/⟨Fe⟩.

2021-11-29 09:32 UTC, correac commented on data/GalaxyStellarMassAlphatoIron/conversion/convertGallazzi2021.py
> +M_star = 10 ** raw[:, 0] * unyt.Solar_Mass * (h_sim / h_obs) ** -2
Yes, I want to directly convert from Gallazzi Msun convention directly to Msun.

Gallazzi gives stellar masses in units of Msun (h/0.7)^2. Now I think that the correct way to calculate M_star is : 
M_star = (
    10 ** raw[:, 0] * unyt.Solar_Mass * (h_obs / 0.7) ** 2
)

2021-11-29 09:32 UTC, correac commented on data/GalaxyStellarMassAlphatoIron/conversion/convertGallazzi2021.py
> +input_filename = "../raw/Gallazzi_2021_ascii.txt"
Fixed.

2021-11-29 09:33 UTC, correac commented
The above figure shows the scatter calculated by Gallazzi, not error bars, but scatter. Since it is quite large, perhaps we can just show the median estimations.

2021-12-01 10:15 UTC, EvgeniiChaikin commented on data/GalaxyStellarMassAlphatoIron/raw/gallazzi_2021_ascii.txt
> +# mass-metallicity data from Gallazzi et al. 2021
Thanks!

2021-12-01 10:19 UTC, EvgeniiChaikin commented
> The above figure shows the scatter calculated by Gallazzi, not error bars, but scatter. Since it is quite large, perhaps we can just show the median estimations.

I don't understand why in this figure the scatter, e.g., at `Mstar = 1e10 Msun` **exceeds 0.4** along the Y-axis while the scatter in the bottom panel of Fig. 4 in Gallazzi's paper does not. Is this to be expected?

2021-12-01 10:28 UTC, correac commented
I think the figure shifts slightly in the x-axis due to the (h/h_obs)^2 factor, and shifts in the y-axis due to the conversion to Asplund+ solar metallicities.

2021-12-01 10:34 UTC, EvgeniiChaikin commented on data/GalaxyStellarMassAlphatoIron/conversion/convertGallazzi2021.py
> +M_star = 10 ** raw[:, 0] * unyt.Solar_Mass * (h_sim / h_obs) ** -2
Yes, it looks like multiplying by ` (h_obs / 0.7) ** 2` is the correct way.

2021-12-01 10:42 UTC, EvgeniiChaikin commented on data/GalaxyStellarMassAlphatoIron/conversion/convertGallazzi2021.py
> +    "The metallicity is expressed as [alpha/Fe]. "
Thanks, Camila!

Do you think we should also mention it in the comment (so that whoever uses these data in `swift-pipeline` knows what **alpha** is) or is it not necessary?

2021-12-01 10:46 UTC, correac commented on data/GalaxyStellarMassAlphatoIron/conversion/convertGallazzi2021.py
> +    "The metallicity is expressed as [alpha/Fe]. "
Yes, better to add it in the comment. I will modify the branch adding the comment and fix the conversion to MStellar.

2021-12-01 11:52 UTC, correac commented on data/GalaxyStellarMassAlphatoIron/conversion/convertGallazzi2021.py
> +    Z_median, scatter=y_scatter, comoving=True, description="Stellar metallicity"
Fixed.

2021-12-01 11:52 UTC, correac commented on data/GalaxyStellarMassAlphatoIron/conversion/convertGallazzi2021.py
> +M_star = 10 ** raw[:, 0] * unyt.Solar_Mass * (h_sim / h_obs) ** -2
Fixed

2021-12-02 09:57 UTC, EvgeniiChaikin approved these changes

2021-12-02 11:11 UTC, bwvdnbro approved these changes

2021-12-02 11:11 UTC, merged