WIP: The azimuthally-averaged and spatially-resolved Kennicutt-Schmidt relations
SWIFTSIM/velociraptor-comparison-data pull request #122
Opened 2022-07-15 14:15 UTC by Fonotec

This is all the data that we need in order to compare with both the neutral (molecular + atomic) and molecular KS relations, both for the azimuthally-averaged and spatially-resolved KS relations. 

Currently, I made my first convert script for the Schruba 2011 dataset. @bwvdnbro let me know any current suggestions to improve the scripts.

After this script I will make the following scripts:
- The azimuthally-averaged neutral KS relation
- The spatially-resolved neutral KS relation
- The spatially-resolved molecular KS relation

2022-07-18 08:02 UTC, bwvdnbro requested changes
I have left an extensive list of comments in one of your scripts. The same comments apply to the other scripts.

Generally:
 - use `scipy.stats.binned_statistic`, it is much faster than any binning algorithm you can come up with yourself
 - try to explain where non trivial conversion factors (e.g. the `1.36` factor) come from
 - use the bin size as scatter for the x variable

2022-07-18 09:50 UTC, bwvdnbro commented
Another thing: could you run the formatting script? As you can see, the CI fails.

2022-07-18 16:14 UTC, Fonotec commented on data/AzimuthallyAveragedMolecularKSRelation/conversion/convertSchruba2011.py
> +sigma_SFR, sigma_SFR_err, sigma_HI, sigma_HI_err, sigma_H2, sigma_H2_err, quality = np.genfromtxt(input_filename, unpack=True, usecols=(3,4,5,6,7,8,10))
Okay, I fixed this in all the files.

2022-07-18 16:16 UTC, Fonotec commented on data/AzimuthallyAveragedMolecularKSRelation/conversion/convertSchruba2011.py
> +Obs_H2 = (sigma_H2)/1.36
I added a comment in each file regarding this, similarly, for the optional factor for Sigma_SFR I also added a comment.

2022-07-20 08:43 UTC, Fonotec commented on data/AzimuthallyAveragedMolecularKSRelation/conversion/convertSchruba2011.py
> +def bin_data_general(array_x, array_y, array_x_bin, x_limit, print_stuff=False):
I added this improvement to the code

2022-07-20 08:43 UTC, Fonotec commented on data/AzimuthallyAveragedMolecularKSRelation/conversion/convertSchruba2011.py
> +    y_array_bin_std_down = np.abs(y_array_bin_std_down - y_array_bin)
That is true, I added this to the code

2022-07-20 08:44 UTC, Fonotec commented on data/AzimuthallyAveragedMolecularKSRelation/conversion/convertSchruba2011.py
> +processed.associate_x(SigmaH2, scatter=None, comoving=False, description="H2 Surface density")
True, I added this change to the code

2022-07-26 13:02 UTC, bwvdnbro approved these changes

2022-07-26 13:10 UTC, merged

2022-07-26 13:11 UTC, bwvdnbro commented
Looks good. I noticed that the CI was not working properly, but I couldn't push to your fork. So I have fixed this and merged this PR manually.