Adding new data for stellar abundance plots
SWIFTSIM/velociraptor-comparison-data pull request #123
Opened 2022-07-18 15:48 UTC by correac

2022-07-19 09:01 UTC, bwvdnbro requested changes
This looks good, but needs some more cleaning up (see comments).

Can you explain why the `Buder2_data.hdf5` file already has the right format? It is nice that it does, but I doubt that it was published that way. Distinguishing between the raw data and the conversion script is useful because it allows us to see exactly what happens to the raw data, and because the script then contains a clear human readable reference to the data. That reference is (probably?) still in the `.hdf5` file, but we cannot see it from the repository anymore. So I don't really like the lack of transparency for this dataset.

2022-07-19 10:39 UTC, correac commented on .gitignore
> +!data/*/Buder21_data.hdf5
Yes, I only have the Buder21_data from James Trayford and not the raw. Let's leave it as exception for now until we can have the raw data + processing file.

2022-07-19 10:40 UTC, correac commented on data/StellarAbundances/conversion/convertTolstoy09.py
> +# CC. No need to convert Tolstoy+ data to Asplund+, this has already been done when
Is it ok if we leave it commented for now? I need to go back to Tolstoy+ to recheck this on a galaxy by galaxy basis.

2022-07-19 10:42 UTC, bwvdnbro commented on .gitignore
> +!data/*/Buder21_data.hdf5
That is acceptable for now, but I would really prefer it if this file was moved to `raw` as well, since it is not compatible with the autoplotter.

2022-07-19 10:45 UTC, correac commented on .gitignore
> +!data/*/Buder21_data.hdf5
But it is not raw data, and the autoplotter does not use it. I do not see which compatibility it needs.

2022-07-22 10:53 UTC, MatthieuSchaller commented on .gitignore
> +!data/*/Buder21_data.hdf5
We may need it in the autoplotter at a later time. It's a bit awkward to have a set of files that can be autoplotted and a set that cannot.

2022-07-25 08:07 UTC, bwvdnbro commented on .gitignore
> +!data/*/Buder21_data.hdf5
Yes, I guess that is the point I wanted to make. Files that are at that level in the directory tree are always assumed to be compatible with the autoplotter. Having a file there that is not is confusing. Files in `raw` can be anything and therefore it is more appropriate to have this file there.

2022-07-25 11:39 UTC, merged