Include some spatially-resolved relations of Abdurro'uf + 2022
SWIFTSIM/velociraptor-comparison-data pull request #125
Opened 2022-08-01 08:34 UTC by Fonotec

@bwvdnbro these are the Kennicutt-Schmidt relations, but also the molecular gas main sequence and the star formation main sequence binned for the new paper of Abdurro'uf + (2022). 

Let me know if you have suggestions.

2022-08-01 15:20 UTC, bwvdnbro requested changes
Looks good! I have left some small comments (the first one applies to all the scripts).

2022-08-01 15:20 UTC, bwvdnbro commented on data/SpatiallyResolvedMolecularGasMainSequence/convert/convertAbdurrouf2022.py
> +Sigma_H2 = 10 ** (Sigma_H2-6.0)
I'm not a big fan of this manual unit conversion. The whole point of using a `unyt_array` with units below is that you don't need to do these conversions manually. The rest of the pipeline knows how to deal with these units. So if the data is in `Mpc/kpc^2`, just use that as a unit.

2022-08-01 15:20 UTC, bwvdnbro commented on data/SpatiallyResolvedNeutralKSRelation/conversion/convertAbdurrouf2022.py
> +Sigma_Hn = (10 ** (Sigma_Hn - 6.0)) / 1.36
Here it would also be useful to add a little comment about the 1.36 correction factor.

2022-08-10 08:02 UTC, Fonotec commented on data/SpatiallyResolvedNeutralKSRelation/conversion/convertAbdurrouf2022.py
> +Sigma_Hn = (10 ** (Sigma_Hn - 6.0)) / 1.36
I left a comment at that line.

2022-08-10 08:02 UTC, Fonotec commented on data/SpatiallyResolvedMolecularGasMainSequence/convert/convertAbdurrouf2022.py
> +Sigma_H2 = 10 ** (Sigma_H2-6.0)
Okay, I did that

2022-08-10 08:17 UTC, Fonotec commented
I forgot to put the bin arrays in the right units.

2022-08-10 08:23 UTC, Fonotec commented
Now it is good to go

2022-08-10 12:57 UTC, bwvdnbro approved these changes

2022-08-10 12:58 UTC, merged