Added Leja+2022 stellar mass - sSFR data.
SWIFTSIM/velociraptor-comparison-data pull request #131
Opened 2022-08-26 10:21 UTC by bwvdnbro

2022-08-28 16:36 UTC, EvgeniiChaikin requested changes
Thank you for the update @bwvdnbro! 

I left several comments in the code diff.

Leja's sSFRs look very interesting! One question -- how did you obtain the raw values?

2022-08-29 08:48 UTC, bwvdnbro commented
Joop obtained the data directly from Leja; they should match exactly what is plotted in Fig. 3 in the paper.

2022-08-29 08:52 UTC, bwvdnbro commented on data/GalaxyStellarMassSpecificStarFormationRate/raw/Leja2022_z0p3.txt
> +8.600,nan,nan,nan,nan,nan
In my experience `matplotlib` knows how to mask out `NaN`s, so I don't think this is necessarily a problem. But it does make little sense to waste storage on rows that will never be used, so I will implement the masking.

2022-08-29 08:55 UTC, bwvdnbro commented on data/GalaxyStellarMassSpecificStarFormationRate/conversion/convertLeja2022.py
> +    sSFR_low = SFR_low / Mstar
Good point. Ideally, we would want to plot the error bars as a shaded region, but the pipeline does not allow that.

My only potential problem with slicing would be that a combination of slicing and masking `NaN`s could result in a non-uniform resampling. But since the only occurrence of `NaN`s is the continuous block at the start of each file, that is actually not really an issue.

2022-08-29 08:57 UTC, bwvdnbro commented on data/GalaxyStellarMassSpecificStarFormationRate/raw/Leja2022_z0p3.txt
> +8.600,nan,nan,nan,nan,nan
Actually, I think it makes more sense to just remove the `NaN` rows from the data files themselves, since in all cases they just provide an offset from the start of the mass range that is below the sensitivity threshold. Having them adds no information.

2022-08-29 09:06 UTC, bwvdnbro commented
I think I have addressed all your comments now.

2022-08-30 08:24 UTC, EvgeniiChaikin approved these changes

2022-08-30 08:25 UTC, EvgeniiChaikin commented
Thank you for handling the comments! I have run the updated version and everything seems to be working as expected.

I don't have anything else to add.

2022-08-30 08:25 UTC, merged

2022-08-30 08:25 UTC, EvgeniiChaikin commented on data/GalaxyStellarMassSpecificStarFormationRate/raw/Leja2022_z0p3.txt
> +8.600,nan,nan,nan,nan,nan
Yes, agreed. Removing NaNs from the raw data files is a better option than masking NaNs out in the script.