Added Strom+2022 gas metallicity data.
SWIFTSIM/velociraptor-comparison-data pull request #132
Opened 2022-08-26 16:34 UTC by bwvdnbro

Adds the 3 fits from Strom et al. (2022) for high redshift gas metallicity (https://ui.adsabs.harvard.edu/abs/2022ApJ...925..116S/abstract).

2022-08-28 10:42 UTC, EvgeniiChaikin requested changes
Thank you for the update @bwvdnbro 

Some small comments are below in the code and I also have two more important comments:

1) This script is currently in the directory in /GalaxyStellarMass**Gas**Metallicity, which is not quite right because in addition to gas-phase metallicities (OH and NH) it also converts data for stellar metallicity (FeH). I think the easiest way to resolve it is to create a second version of this script, put the second version in /GalaxyStellarMass**Stellar**Metallicity and make it only convert FeH; while in this version convert only OH and NH.

2) The gas-phase metallicity in our pipeline is shown as 12 + log(O/H) so the data produced by this script can be directly shown in those plots. However, the plots with stellar metallicity in the pipeline show Z/Z_sun (or in units of [Fe/H], 10 ** [Fe/H]), whereas this script gives [Fe/H] (or log Z/Z_sun). This means that in order to put Strom's FeH data on our plots with stellar metallicity, we will need to transform the y values produced by this script as y -> 10**y. This is another reason why it is good to separately convert metallicity for gas phase and stars (see my point 1).

2022-08-28 10:42 UTC, EvgeniiChaikin commented on data/GalaxyStellarMassGasMetallicity/conversion/convertStrom2022.py
> +M_star = unyt.unyt_array(np.logspace(9.0, 11.3, 100), units="Msun")
```suggestion
M_star = unyt.unyt_array(np.logspace(9.0, 11.3, 20), units="Msun")
```
With so many points as 100 it is impossible to distinguish individual error bars. 

![stellar_mass_star_fe_over_h_mol_lofloor_50_old](https://user-images.githubusercontent.com/20153933/187068888-248fc696-fc8a-4f91-8d34-ae566d88b982.png)

Le'ts make it 20. Then the error bars will look as follows

![stellar_mass_star_fe_over_h_mol_lofloor_50](https://user-images.githubusercontent.com/20153933/187068877-17b2fc44-d839-4cd5-aa81-0ca79b2de699.png)

2022-08-28 10:42 UTC, EvgeniiChaikin commented on data/GalaxyStellarMassGasMetallicity/conversion/convertStrom2022.py
> +    "FeH": {"alpha": (-0.69, 0.02), "beta": (0.17, 0.22), "label": "[Fe/H]"},
It should be
```suggestion
    "FeH": {"alpha": (-0.69, 0.02), "beta": (0.17, 0.05), "label": "[Fe/H]"},
```
according to Table 1 from https://arxiv.org/pdf/2111.06410.pdf

2022-08-28 10:42 UTC, EvgeniiChaikin commented on data/GalaxyStellarMassGasMetallicity/conversion/convertStrom2022.py
> +comment = "The median stellar mass is 1e10 Msun."
I would also indicate in the comment that 

- This is **a fit** to the data containing 195 star-forming high-redshift galaxies
- Strom et al (2022) use solar abundancies from Asplund et al. (2009), so no corrections are needed (because for Colibre we also use Asplund et al. (2009))

2022-08-28 10:42 UTC, EvgeniiChaikin commented on data/GalaxyStellarMassGasMetallicity/conversion/convertStrom2022.py
> +redshift = np.array([2.0, 2.7])
Let's expand the range a little bit, so whenever we make plots at z \approx 2 or z \approx 3, these data are always included.
```suggestion
redshift = np.array([1.9, 3.1])
```

2022-08-28 10:42 UTC, EvgeniiChaikin commented on data/GalaxyStellarMassGasMetallicity/conversion/convertStrom2022.py
> +    name = f"Stellar mass - Gas phase metallicity relation ({label})"
**OH** and **NH** are indeed gas-phase metallicities but **FeH** is stellar metallicity.

```suggestion
    name = f"Stellar mass - Metallicity relation ({label})"
```

2022-08-28 10:42 UTC, EvgeniiChaikin commented on data/GalaxyStellarMassGasMetallicity/conversion/convertStrom2022.py
> +        description=f"Gas phase metallicity ({label})",
See my comment above
```suggestion
        description=f"Metallicity ({label})",
```

2022-08-29 09:19 UTC, bwvdnbro commented
I think I have implemented all the changes you requested.

2022-08-29 12:23 UTC, EvgeniiChaikin approved these changes

2022-08-29 12:24 UTC, EvgeniiChaikin commented
Thanks! It all looks good now! Here are some example

![stellar_mass_gas_sf_metallicity_total_lom_30](https://user-images.githubusercontent.com/20153933/187200231-7a0e1f36-ad4f-40cb-8ecf-e53f0bbdfc2f.png)
![stellar_mass_star_fe_over_h_lom_50](https://user-images.githubusercontent.com/20153933/187200235-b156885f-f792-413c-b4c7-06995b850c4d.png)

2022-08-29 12:25 UTC, merged