Add terrazas 2017 BH mass vs. SFR data
SWIFTSIM/velociraptor-comparison-data pull request #133
Opened 2022-09-01 16:29 UTC by MatthieuSchaller

Will be interesting to compare how rapidly our model(s) quench via AGN

2022-09-01 16:29 UTC, MatthieuSchaller commented
I'll add the plots to the pipeline next.

2022-09-02 15:27 UTC, bwvdnbro requested changes
I think the scatter is provided in the wrong way: you need to provide the error and not the upper and lower limit.

With the current values of scatter, the data looks like this:
![Terrazas_before](https://user-images.githubusercontent.com/7336967/188182448-d5720663-11ca-49c0-9807-bd5ddc6f59c2.png)

While I think it should actually look like this:
![Terrazas_after](https://user-images.githubusercontent.com/7336967/188182445-2f0f7902-214b-4d3d-9026-53fcda8d39ef.png)

The script `plot_individual_dataset.py` is quite useful for visual inspection of the newly added data.

2022-09-02 15:27 UTC, bwvdnbro commented on data/BlackHoleMassStarFormationRate/conversion/convertTerrazas2017.py
> +SFR_scatter = unyt.unyt_array([SFR_lo, SFR_hi])
You need something like
```
SFR_scatter = unyt.unyt_array([SFR - SFR_lo, SFR_hi - SFR])
```
The scatter is the actual error on the values and not the lower and upper bounds.

2022-09-02 15:27 UTC, bwvdnbro commented on data/BlackHoleMassStarFormationRate/conversion/convertTerrazas2017.py
> +BH_mass_scatter = unyt.unyt_array([BH_mass_lo, BH_mass_hi])
Same here.

2022-09-02 18:49 UTC, MatthieuSchaller commented
Thanks. I think I will never remember correctly how matplotlib's errobar function works. Somehow the choice they made feels non-intuituve but by now I should know better.

2022-09-05 15:06 UTC, bwvdnbro commented
For me this is good to go. I don't know if you want to wait for Evgenii's review before merging this?

2022-09-05 19:03 UTC, MatthieuSchaller commented
We can go ahead. I'll add another review on the plotting side.

2022-09-06 09:44 UTC, merged