Add the Thorne+21 high-z GSMF data (DEVILS survey)
SWIFTSIM/velociraptor-comparison-data pull request #135
Opened 2022-09-09 15:54 UTC by MatthieuSchaller

2022-09-13 11:55 UTC, EvgeniiChaikin requested changes
Thanks @MatthieuSchaller !

Besides small comments in the code, I have two questions,

- Where does the raw data come from? Is it private communication or I can find it in the paper?

- I tried plotting the data at several redshirts. At `z=2.5` everything looks fine but at `z=0` the error bars are suspiciously large and the data itself is a bit off compared to GSMFs from the other surveys (see the plots below)

![adaptive_stellar_mass_function_50_z2p5](https://user-images.githubusercontent.com/20153933/189893790-8d07d432-4947-4627-9e30-39a6792f61cf.png)

![adaptive_stellar_mass_function_50_z0p0](https://user-images.githubusercontent.com/20153933/189893897-43858edd-9b0f-4afb-a9d6-c58c3a2c9c6c.png)

2022-09-13 11:55 UTC, EvgeniiChaikin commented on data/GalaxyStellarMassFunction/conversion/convertThorne2021.py
> +    "from the DEVILS suvery (D10-COSMOS field)."
```suggestion
    "from the DEVILS survey (D10-COSMOS field)."
```

2022-09-13 11:55 UTC, EvgeniiChaikin commented on data/GalaxyStellarMassFunction/conversion/convertThorne2021.py
> +    f"GSMF at redshifts {min(redshifts)}<z{max(redshifts)}, "
```suggestion
    f"GSMF at redshifts {min(redshifts)}<z<{max(redshifts)}, "
```

2022-09-13 11:55 UTC, EvgeniiChaikin commented on data/GalaxyStellarMassFunction/conversion/convertThorne2021.py
> +    redshift = z
I don't understand the meaning of this line

2022-09-13 11:55 UTC, EvgeniiChaikin commented on data/GalaxyStellarMassFunction/conversion/convertThorne2021.py
> +    mass = unyt.unyt_array(M, units=unyt.Solar_Mass)
Here you want
```suggestion
    mass = unyt.unyt_array(10 ** M, units=unyt.Solar_Mass)
```

2022-09-13 15:17 UTC, MatthieuSchaller commented on data/GalaxyStellarMassFunction/conversion/convertThorne2021.py
> +    redshift = z
Fixed.

2022-09-13 15:17 UTC, MatthieuSchaller commented on data/GalaxyStellarMassFunction/conversion/convertThorne2021.py
> +    f"GSMF at redshifts {min(redshifts)}<z{max(redshifts)}, "
Fixed.

2022-09-13 15:17 UTC, MatthieuSchaller commented on data/GalaxyStellarMassFunction/conversion/convertThorne2021.py
> +    "from the DEVILS suvery (D10-COSMOS field)."
Fixed.

2022-09-13 20:15 UTC, EvgeniiChaikin commented on data/GalaxyStellarMassFunction/conversion/convertThorne2021.py
> +    0.51,
If the data looks bad at `z=0` (compared to the other data we have at these z), would it be better to not show it at all at these low `z`? This can be realised, e.g., by commenting out a few first numbers from this list.

2022-09-13 20:18 UTC, EvgeniiChaikin approved these changes

2022-09-13 20:40 UTC, MatthieuSchaller commented on data/GalaxyStellarMassFunction/conversion/convertThorne2021.py
> +    0.51,
Can we rather choose the range to use in the pipeline itself?

2022-09-14 07:14 UTC, EvgeniiChaikin commented on data/GalaxyStellarMassFunction/conversion/convertThorne2021.py
> +    0.51,
I am not sure. Currently, there is no such functionality. Here we store Thorne's data as a _single_ file that has GSMFs at _multiple_ z. When we add this data to the plot, the pipeline will always try to find Thorne's GSMF that is closest to the snapshot's redshift. So if we make our plots at `z=0`,  the pipeline will use Thorne at `z=0.064`


If we would like to exclude certain redshifts in a multi-z file at the moment when we make plots, we would need to make a change in the velociraptor-python library. Do you think it would be worth it?

2022-09-14 07:23 UTC, MatthieuSchaller commented on data/GalaxyStellarMassFunction/conversion/convertThorne2021.py
> +    0.51,
In principle, yes, as there is nothing fundamentally wrong with the low-z data here. 

But, that's a big change so don't think we should embark in that. So we could apply your proposed solution here.
From Fig. 9 of https://arxiv.org/pdf/2011.13605.pdf, I propose we keep the data from z>0.2.
What do you think?

2022-09-14 08:06 UTC, EvgeniiChaikin commented on data/GalaxyStellarMassFunction/conversion/convertThorne2021.py
> +    0.51,
We could comment out the first two numbers, `0.064` and `0.12`, and change Delta z from  `0.25` to `0.15` in 

`processed.associate_redshift(z, redshift_lower=z - 0.25, redshift_upper=z + 0.25)`

2022-09-14 11:41 UTC, MatthieuSchaller commented on data/GalaxyStellarMassFunction/conversion/convertThorne2021.py
> +    0.51,
I have changed that to use something slightly more dynamic. Let me know what you think.

Also, I have cancelled the first three outputs.

2022-09-14 14:15 UTC, EvgeniiChaikin commented on data/GalaxyStellarMassFunction/conversion/convertThorne2021.py
> +    0.51,
I am happy with the current version. Let's merge it! 

PS Here's the `z=0` plot after today's changes

![adaptive_stellar_mass_function_50](https://user-images.githubusercontent.com/20153933/190178798-a02cabb5-7ff5-4b4d-b6da-47477ed44c36.png)

2022-09-14 15:19 UTC, MatthieuSchaller commented on data/GalaxyStellarMassFunction/conversion/convertThorne2021.py
> +    0.51,
Wait, that's not great. Ideally that dataset should no appear at all at z=0.

2022-09-14 15:20 UTC, MatthieuSchaller commented on data/GalaxyStellarMassFunction/conversion/convertThorne2021.py
> +    0.51,
I put a limit of 0.2 for the lowest bin, should I not expect the code to honour that?

2022-09-17 19:00 UTC, merged