SNIa rate data compilation
SWIFTSIM/velociraptor-comparison-data pull request #138
Opened 2022-09-29 11:15 UTC by Fonotec

This is my current SNIa rate data compilation that is mainly centred around the following datasets:
Smith+2012
Kistler+2013
Graur+2015
Graur+2017
Wiseman+2021
I did not include the Brown+2019 data that Fire compares with. I am waiting for a reply from the author also this one has no normalisation so might require some thinking. 

If possible I also added the SE SNe and SNII datasets in the repository as this is presented in the same papers and might be useful in the future. 

Let me know what you think.

2022-09-29 12:39 UTC, bwvdnbro requested changes
A lot of your files do the same things multiple times for different files. That can be done more elegantly with some kind of loop.

There are some raw files that are not used by any conversion script. Did you accidentally copy those?

This pull request seems to contain the code changes from #128. Please remove those.

A more fundamental problem is that your conversion scripts are in a folder called `convert`, while this should really by `conversion`. As a result, neither `convert.py` nor the formatting script pick up your scripts. Can you please rename your folders, test the conversion script and run the formatting script?

2022-09-29 12:39 UTC, bwvdnbro commented on data/GalaxyStellarMassSNIaRate/convert/convertGraur2017.py
> +from velociraptor.observations.objects import ObservationalData
There is a lot of code duplication in this file. Could you use some kind of loop to avoid that?

2022-09-29 12:39 UTC, bwvdnbro commented on data/GalaxyStellarMassSNIaRate/convert/convertSmith2012.py
> +from velociraptor.observations.objects import ObservationalData
You could also avoid some code duplication here.

2022-09-29 12:39 UTC, bwvdnbro commented on data/GalaxyGasMetallicityCoreCollapseSNeRatePerStellarMass/convert/convertGraur2017.py
> +from velociraptor.observations.objects import ObservationalData
You could avoid some code duplication here by using a loop.

2022-09-29 12:39 UTC, bwvdnbro commented on data/GalaxyStellarMassSNIaRate/raw/Graur_2015_SF.txt
> +# log Mstar(+10) err_d err_up SNIaR per Mstar err_d x2 err_up x 2
There is no conversion script for this file.

2022-09-29 12:39 UTC, bwvdnbro commented on data/GalaxyStellarMassSNIaRate/raw/Graur_2015_all.txt
> +# log Mstar(+10) err_d err_up SNIaR per Mstar err_d x2 err_up x 2
There is no conversion script for this file.

2022-09-29 12:39 UTC, bwvdnbro commented on data/GalaxyStellarMassSNIaRatePerStellarMass/convert/convertGraur2015.py
> +from velociraptor.observations.objects import ObservationalData
Avoidable code duplication.

2022-09-29 12:39 UTC, bwvdnbro commented on data/SpatiallyResolvedMolecularGasMainSequence/convert/convertPessa2021.py
> +from velociraptor.observations.objects import ObservationalData
I thought this file was added by a different pull request already?

2022-10-20 15:50 UTC, Fonotec commented on data/GalaxyStellarMassSNIaRate/raw/Graur_2015_SF.txt
> +# log Mstar(+10) err_d err_up SNIaR per Mstar err_d x2 err_up x 2
There is now

2022-10-20 15:50 UTC, Fonotec commented on data/GalaxyStellarMassSNIaRate/raw/Graur_2015_all.txt
> +# log Mstar(+10) err_d err_up SNIaR per Mstar err_d x2 err_up x 2
There is now

2022-10-24 08:50 UTC, Fonotec commented on data/GalaxyStellarMassSNIaRate/convert/convertSmith2012.py
> +from velociraptor.observations.objects import ObservationalData
This has been fixed

2022-10-24 08:50 UTC, Fonotec commented on data/GalaxyGasMetallicityCoreCollapseSNeRatePerStellarMass/convert/convertGraur2017.py
> +from velociraptor.observations.objects import ObservationalData
Done

2022-10-24 09:18 UTC, Fonotec commented
@bwvdnbro, this is the updated version with your suggestions, I think all datasets have a conversion script. Let me know what you think

2022-10-25 13:09 UTC, bwvdnbro requested changes
Thanks! I have left some more comments. This is almost good to go.

2022-10-25 13:09 UTC, bwvdnbro commented on data/GalaxyGasMetallicityCoreCollapseSNeRatePerStellarMass/conversion/convertGraur2017.py
> +        )
It might be cleaner to just create an additional array with descriptions at the top and then use
```
processed.associate_y(SNuM, scatter=SNuM_err, comoving=False, description=descriptions[i])
```
same for the names. That way, all the information is in once place.

Even cleaner would be to just get rid of the `i` variable all together and to instead do something like this:
```
variations = [
    ("../raw/SE_SNe_rate_vs_gas_metallicity_Graur_2017.txt", ""Graur2017_SE_SNe.hdf5", "Gas metallicity - SE SN Rate per Stellar Mass", "SE SNe rate per stellar mass"),
    ("../raw/SNII_rate_vs_gas_metallicity_Graur_2017.txt", ""Graur2017_SNII.hdf5", "Gas metallicity - SNII Rate per Stellar Mass", "SNII rate per stellar mass"),
]
for input_filename, output_filename, name, description in variations:
    ...
```
you could also limit the amount of information that is actually looped over:
```
variations = [
    ("SE_SNe", "SE SNe rate per stellar mass"),
    ("SNII", "SNII rate per stellar mass"),
]
for file_prefix, description in variations:
    name = f"Gas metallicity - {description}"
    input_filename = f"../raw/{file_prefix}_rate_vs_gas_metallicity_Graur_2017.txt"
    output_filename = f"Graur2017_{file_prefix}.hdf5"
    ...
```

2022-10-25 13:09 UTC, bwvdnbro commented on data/GalaxyStellarMassSNIaRate/conversion/convertGraur2015.py
> +        comment = "LOSS [$z \\approx 0.075$, active only]"
I would also prefer it if this was handled in a cleaner way. It is a lot clearer if the different comments are defined in the same place as the different file names.

2022-10-25 13:09 UTC, bwvdnbro commented on data/GalaxyStellarMassSNIaRate/conversion/convertGraur2017.py
> +        comment = "LOSS [$z \\approx 0.2$, active only]"
Same comment (pun intended) as above.

2022-10-25 13:09 UTC, bwvdnbro commented on data/GalaxyStellarMassSNIaRate/conversion/convertSmith2012.py
> +        comment = "SDSS-II SN Survey [$0.05<z<0.25$, passive only]"
See earlier remark.

2022-10-25 13:09 UTC, bwvdnbro commented on data/GalaxyStellarMassSNIaRatePerStellarMass/conversion/convertGraur2015.py
> +        comment = "LOSS [$z \\approx 0.075$, active only]"
See before.

2022-10-25 13:09 UTC, bwvdnbro commented on data/GalaxyStellarMassSNIaRatePerStellarMass/conversion/convertGraur2017.py
> +        comment = "LOSS [$z \\approx 0.2$, active only]"
See before.

2022-10-25 13:09 UTC, bwvdnbro commented on data/GalaxyStellarMassSNIaRatePerStellarMass/conversion/convertSmith2012.py
> +        comment = "SDSS-II SN Survey [$0.05<z<0.25$, passive only]"
See before

2022-10-25 13:09 UTC, bwvdnbro commented on data/SpecificStarFormationRateCoreCollapseSNeRatePerStellarMass/conversion/convertGraur2017.py
> +        name = "Specific Star Formation Rates-SNII Rate per Stellar Mass"
See before.

2022-10-25 13:09 UTC, bwvdnbro commented on data/StarFormationRateCoreCollapseSNeRatePerStellarMass/conversion/convertGraur2017.py
> +        name = "Star Formation Rates-SNII Rate per Stellar Mass"
See before

2022-10-25 13:09 UTC, bwvdnbro commented on data/StarFormationRateCoreCollapseSNeRatePerStellarMass/conversion/convertGraur2017.py
> +        )
See before.

2022-10-26 08:58 UTC, Fonotec commented
@bwvdnbro I incorporated your remaining suggestions, let me know what you think.

2022-10-26 10:10 UTC, bwvdnbro approved these changes

2022-10-26 10:11 UTC, merged