Add AGN bolometric luminosity function
SWIFTSIM/velociraptor-comparison-data pull request #141
Opened 2022-10-21 15:30 UTC by FHusko

This adds a lot of AGN bolometric LF data in a single file, with data points from redshifts 0.2 to 7, mostly at intervals of 0.2. These observations are from 5 separate wavelength bands, but were converted into bolometric luminosities in the original paper. The 5 separate bands are plotted separately, however, from 5 separate hdf5 files.

Something is apparently not done correctly in the conversion script, since down the line, when a script is used to plot the data, for some reason the z=1 dataset in the hdf5 file gets displayed, regardless of the redshifts in the simulations.

2022-10-23 17:01 UTC, MatthieuSchaller commented
The automated checks are failing so that will need to be addressed.

2022-10-23 18:40 UTC, FHusko commented
I had forgotten to run the formatting script. Should be okay now.

2022-10-25 11:01 UTC, EvgeniiChaikin requested changes
Thanks @FHusko! 

I added a few suggestions to your code. 

I marked this PR as _changes required_ because we haven't figured out yet why you always get redshift `z=1`. Can you please point me to the code where I could see how you include this observational data?

2022-10-25 13:23 UTC, FHusko commented on data/BlackHoleAGNBolometricLuminosityFunction/conversion/convertShen2020.py
> +delimiter = None
No, it was used in the `np.loadtxt` function (see below), but when that was removed, I didn't notice that `delimited` remained. Removed now.

2022-10-25 13:24 UTC, FHusko commented on data/BlackHoleAGNBolometricLuminosityFunction/conversion/convertShen2020.py
> +)  # np.loadtxt(input_filename, delimiter=delimiter, dtype = ('str','float','float','float','float','float'),usecols=(0, 1, 2, 3, 4, 5))
This was left over from the copied script - most scripts use the `np.loadtxt` function, but I had to use `np.genfromtxt` since the former does not allow mixed (string and float) entries (columns), while this one does.

2022-10-25 13:24 UTC, FHusko commented on data/BlackHoleAGNBolometricLuminosityFunction/conversion/convertShen2020.py
> +]
Thanks. I was having issues with doing something similar using the the usual `+` string concatenation, for some reason, but this works.

2022-10-25 13:29 UTC, FHusko commented on data/BlackHoleAGNBolometricLuminosityFunction/conversion/convertShen2020.py
> +            L[(wavelength_band == wavelength_band_types[i]) & (redshifts == z)],
Thanks for catching this. This is one of those cases when you think you will need something once or twice, but then it just pops up more often than you think it will.

2022-10-26 12:32 UTC, EvgeniiChaikin commented on data/BlackHoleAGNBolometricLuminosityFunction/conversion/convertShen2020.py
> +    plot_as = "points"
The current code looks fine to me.

I meant that you could move

```
    bibcode = "2020ApJ.892.17D"
    name = "AGN Bolometric Luminosity Function"
    plot_as = "points"
```

outside.

2022-10-26 12:33 UTC, EvgeniiChaikin commented on data/BlackHoleAGNBolometricLuminosityFunction/conversion/convertShen2020.py
> +processed = ObservationalData()
you do not need to define `processed` here.

2022-10-26 12:37 UTC, EvgeniiChaikin commented
Thanks for the changes @FHusko! I tested your script and it works fine for me. Do you still have the problem that the data is only showing up at `z=1`?

If so, can you please send me your code that makes the AGN bolometric luminosity plot with this PR's observational data, which appears to only exist at `z=1`?

2022-10-26 15:49 UTC, FHusko commented on data/BlackHoleAGNBolometricLuminosityFunction/conversion/convertShen2020.py
> +    plot_as = "points"
Ah, okay, thanks (the highlighted code wasn't showing here properly for some reason, yesterday). Moved that out now.

2022-10-26 15:49 UTC, FHusko commented on data/BlackHoleAGNBolometricLuminosityFunction/conversion/convertShen2020.py
> +processed = ObservationalData()
Thanks, I don't know what that was doing there.

2022-10-29 16:47 UTC, EvgeniiChaikin commented
Hi @FHusko!

I have checked how this observational data is included in your script.

Because it is a **multi-redshift** data, when you load it you need to specify at which z you intend to plot it. This is currently not done in your script.

To do this, you need to call `load_observations()`

as
`obs = load_observations(observation, redshift_bracket=[snp_redshift-delta_z, snp_redshift+delta_z])`
instead of 
`obs = load_observations(observation)`

The snapshot redshift, `snp_redshift`, can be taken from `snapshot.metadata.redshift`, while the size of the redshift window in which the script will search for the available observational data, `delta_z`, can be any small number, e.g., `delta_z=0.1`

Since I have checked that the data in this pull request behaves as expected, I think the PR is ready to be merged.

2022-10-29 16:47 UTC, EvgeniiChaikin approved these changes

2022-10-30 11:19 UTC, FHusko commented
@EvgeniiChaikin Thanks! The script now works correctly with the change you suggested.

2022-10-31 09:50 UTC, merged