Add Khusanova data
SWIFTSIM/velociraptor-comparison-data pull request #158
Opened 2023-04-13 12:30 UTC by Moyoxkit

This adds the Khusanova 2021 data to the Star formation history data.

To make this work with the script this requires the addition of the data to
https://github.com/SWIFTSIM/pipeline-configs/blob/8a570af60dcec1992b7ef5239c40dd2ef7ec97e2/colibre/scripts/star_formation_history.py#L138
The correct label for this data is FIR (just like what Gruppioni should also be).

2023-04-16 14:50 UTC, EvgeniiChaikin requested changes
Thanks for the update @Moyoxkit 

I added a couple of small comments to polish the script. 

My only major comment is about the value of the second point in the data set. I am not sure whether the current value is correct. 

After you update your script guided by my comments, please also run the `format.sh` script. After that, I will merge this branch.

2023-04-16 14:50 UTC, EvgeniiChaikin commented on data/StarFormationRateHistory/conversion/convertKhusanova2021.py
> +    name = f"Star formation rate density from Enia et al. (2022)"
```suggestion
    name = "Star formation rate density from Khusanova et al. (2021)"
```

2023-04-16 14:50 UTC, EvgeniiChaikin commented on data/StarFormationRateHistory/conversion/convertKhusanova2021.py
> +    processed.associate_redshift(z)
The (average) redshift of a dataset should always be one number.
```suggestion
    processed.associate_redshift(np.mean(z))
```

2023-04-16 14:50 UTC, EvgeniiChaikin commented on data/StarFormationRateHistory/conversion/convertKhusanova2021.py
> +    processed.associate_x(a_bin, comoving=False, description="Cosmic scale factor")
If the dataset has no scatter along the X-axis, the pipeline requires the user to inform the pipeline about this by providing `scatter=None`.
```suggestion
    processed.associate_x(
        a_bin, scatter=None, comoving=False, description="Cosmic scale factor"
    )
```

2023-04-16 14:50 UTC, EvgeniiChaikin commented on data/StarFormationRateHistory/raw/sfr_khusanova2021.dat
> +#   based on Almao radio observations from the ALPINE survey
```suggestion
#   based on ALMA radio observations from the ALPINE survey
```

2023-04-16 14:50 UTC, EvgeniiChaikin commented on data/StarFormationRateHistory/raw/sfr_khusanova2021.dat
> +5.5  -1.38  0.28  0.36
Are you sure these numbers are correct? In the paper, I found -1.60 instead of -1.38. 

Can you also say in this file which table you took the data from?

2023-04-18 14:33 UTC, Moyoxkit commented on data/StarFormationRateHistory/raw/sfr_khusanova2021.dat
> +5.5  -1.38  0.28  0.36
Yeah this is from table 2 and it's a typo in the table

2023-04-20 10:35 UTC, EvgeniiChaikin commented on data/StarFormationRateHistory/conversion/convertKhusanova2021.py
> +    MultiRedshiftObservationalData,
```suggestion
```

2023-04-25 11:27 UTC, EvgeniiChaikin approved these changes

2023-04-25 11:28 UTC, merged