[WiP] Adding new data for gas metallicity plots
SWIFTSIM/velociraptor-comparison-data pull request #179
Opened 2023-11-05 20:31 UTC by correac

New datasets from Hayden-Pawson+ (2022), Nicholls+ (2017) and Berg+ (2020) to complement the new gas phase C/O-O/H and N/O-O/H relations.

2023-11-08 10:17 UTC, MatthieuSchaller commented
Note that the checks are failing. See above.

2023-11-08 10:44 UTC, correac commented
@MatthieuSchaller The error occurs in > 
`Script data/GalaxyH2MassFunction/conversion -> "python3 -W error -W ignore::UserWarning convertFletcher2021.py ../../../cosmology.py" failed.`
I'm not sure why that happens. I did not modify anything other than the data in folder GalaxyStellarMassGasMetallicity.

2023-11-08 13:27 UTC, robjmcgibbon requested changes
https://github.com/SWIFTSIM/velociraptor-comparison-data/pull/181/ fixes the issue that is currently causing the check to fail. Please rebase the master branch

2023-11-08 13:27 UTC, robjmcgibbon commented on data/GalaxyStellarMassGasMetallicity/conversion/convertHayden2022.py
> +processed.associate_name(name)
You don't redefine name, it's still set as "Stellar mass - Gas phase N/O relation"

2023-11-09 18:13 UTC, MatthieuSchaller commented
Thanks Rob!

2023-11-29 14:03 UTC, MatthieuSchaller commented
Is this still [WIP]?

2023-11-30 09:05 UTC, correac commented on data/GalaxyStellarMassGasMetallicity/conversion/convertHayden2022.py
> +processed.associate_name(name)
Fixed!

2024-01-10 15:01 UTC, correac commented
New datasets from Hayden-Pawson+ (2022), Nicholls+ (2017) and Berg+ (2020) to complement the gas phase C/O-O/H and N/O-O/H relations. The data is shown below. @MatthieuSchaller and @robjmcgibbon you can review the changes, for me this PR is ready to be reviewed and merged.

![image](https://github.com/SWIFTSIM/velociraptor-comparison-data/assets/35491033/5c94a008-96ac-4fc1-83d4-00b156dd3690)
![image](https://github.com/SWIFTSIM/velociraptor-comparison-data/assets/35491033/4396509c-d651-47f2-bb51-a1dddd31c741)

2024-01-10 16:15 UTC, robjmcgibbon approved these changes

2024-01-12 13:10 UTC, merged