Add binned BH mass - stellar mass observational data
SWIFTSIM/velociraptor-comparison-data pull request #188
Opened 2023-11-20 14:51 UTC by FHusko

This adds two data files and conversion scripts for a new BH mass - stellar mass plot. The plot is the same as the usual one, but the observational data (Graham & Sahu 2023 and Terrazas et al. 2017) are binned using fractions of morphological types as well as passive fractions. This then yields a precise median relation of BH mass and stellar mass that can be used for calibration.

2023-11-20 15:01 UTC, FHusko commented
When I run the formatting script, I get the following error:
```
The typed_ast package is required but not installed.
You can upgrade to Python 3.8+ or install typed_ast with
`python3 -m pip install typed-ast`.
```
I have tried this with multiple versions of python, 3.8 and above. I even try installing typed-ast with different versions, the installation is done successfully, and yet I get the same error as above.

2024-03-04 16:17 UTC, robjmcgibbon requested changes
Couple of comments, mainly requesting you to combine the scripts with duplicated code. I was able to run the formatting script on cosma with the following modules `module load gnu_comp/11.1.0 openmpi/4.1.1 python/3.10.1`.

2024-03-04 16:17 UTC, robjmcgibbon commented on data/BlackHoleAccretionHistory/conversion/convertPouliasis2024_low.py
> +BHARD_high = unyt.unyt_array(10**raw[:, 2], "Msun / yr / Mpc**3")
Similarly for this data, can you combine with the other script by doing a loop where you change the indices of the data you read in?

2024-03-04 16:17 UTC, robjmcgibbon commented on data/BlackHoleAccretionHistory/conversion/convertShen2020_high.py
> +BLD_high = 10**unyt.unyt_array(raw[:, 6], "dimensionless") * unyt.erg / (unyt.s * unyt.Mpc**3)
Same for these two Shen scripts

2024-03-04 16:17 UTC, robjmcgibbon commented on data/GalaxyStellarMassBlackHoleMass/conversion/convertGraham2023_binned.py
> +M_star = (10 ** data[:, 0]) * unyt.Solar_Mass
The convertGraham2023.py script has a stellar mass correction. Is that needed here too?

2024-03-05 15:26 UTC, FHusko commented on data/BlackHoleAccretionHistory/conversion/convertAnnana2020_low.py
> +radiative_efficiency = 0.34
Yes, that is the only difference, and indeed it is easy to create the two files through just one script. I've modified it now.

2024-03-05 15:26 UTC, FHusko commented on data/BlackHoleAccretionHistory/conversion/convertPouliasis2024_low.py
> +BHARD_high = unyt.unyt_array(10**raw[:, 2], "Msun / yr / Mpc**3")
Same as above.

2024-03-05 15:26 UTC, FHusko commented on data/BlackHoleAccretionHistory/conversion/convertShen2020_high.py
> +BLD_high = 10**unyt.unyt_array(raw[:, 6], "dimensionless") * unyt.erg / (unyt.s * unyt.Mpc**3)
Done, same as above.

2024-03-05 15:27 UTC, FHusko commented on data/GalaxyStellarMassBlackHoleMass/conversion/convertGraham2023_binned.py
> +M_star = (10 ** data[:, 0]) * unyt.Solar_Mass
Thanks for spotting that, I hadn't noticed it! I didn't convert the stellar masses when binning, so I do it now in the script.

2024-03-06 09:43 UTC, robjmcgibbon commented
Thanks! Could you please remove the _high and _low scripts using `git rm`, and then run the formatter over all scripts. If you're still having difficulty running it on cosma for some reason then I could do it.

2024-03-06 14:26 UTC, FHusko commented
I've removed the duplicate scripts (sorry, thought I had already done it).

I can't seem to run the formatting script. With python 3.10.12 (I seem to need to use python > 3.6 in order to actually process all the observational data), I get the following warning when running the formatting script:
```
You can upgrade to Python 3.8+ or install typed_ast with
`python3 -m pip install typed-ast`.
```
This is despite using pyton >3.8 and having installed typed_ast.

2024-03-06 15:27 UTC, robjmcgibbon commented
Could you please merge https://github.com/FHusko/velociraptor-comparison-data/pull/1

2024-03-07 08:09 UTC, robjmcgibbon approved these changes

2024-03-07 08:45 UTC, merged