Composite Neutral Gas Data
SWIFTSIM/velociraptor-comparison-data pull request #75
Opened 2021-02-23 15:43 UTC by wmfw23

Neutral gas fraction data by combining Catinella+18 and Saintonge+17 data sets.

2021-02-23 16:02 UTC, JBorrow commented
I've assigned @EvgeniiChaikin to give this a draft review as he'll be taking over the maintenance of the repo once I leave for MIT

2021-02-28 20:44 UTC, EvgeniiChaikin requested changes
Hi @wmfw23 I finished my review and sorry for the delay.

I left a number of comments here and there whose main goal is to improve the readability of the files.

Note that the comments I wrote in `convertCatinella2018.py` are also relevant for `convertCatinellaSaintongeComposite.py` 

Also, can you please show a few examples from the pipeline with these new data on the plots? I want to make sure everything is displayed and behaves correctly.

2021-02-28 20:44 UTC, EvgeniiChaikin commented on data/GalaxyColdGasFractions/conversion/convertCatinella2018.py
> +    if i < 3:
Can you please add a few short comments to this section explaining what is going on here? Otherwise, it is difficult to follow

2021-02-28 20:44 UTC, EvgeniiChaikin commented on data/GalaxyColdGasFractions/conversion/convertCatinella2018.py
> +import itertools as it
`intertools` and `re` are not used in this file (and the same is also true for convertCatinellaSaintongeComposite.py)

2021-02-28 20:44 UTC, EvgeniiChaikin commented on data/GalaxyColdGasFractions/conversion/convertCatinella2018.py
> +ORIGINAL_H = 0.7
If this value of h was used in Catinella2018, can you please rename this variable it to `h_Catinella2018` or add a comment above that the value of 0.7 comes from this paper?

2021-02-28 20:44 UTC, EvgeniiChaikin commented on data/GalaxyColdGasFractions/conversion/convertCatinella2018.py
> +    x_err = x_vals * 0.0
If the data provides no scatter it is probably better to set `scatter=None` (in function `processed.associate_x/y`) instead of defining arrays with zero errors

2021-02-28 20:44 UTC, EvgeniiChaikin commented on data/GalaxyColdGasFractions/conversion/convertCatinella2018.py
> +        comoving=0,
`comoving` is a `bool`; please use `True` of `False` for clarity

2021-02-28 20:54 UTC, EvgeniiChaikin commented on data/GalaxyColdGasFractions/conversion/convertCatinella2018.py
> +citation = "Catinella et al. (2018), z = 0"
Ah, sorry, forgot to say -  there is no need to indicate redshift in the citation because otherwise it will appear twice in the plot

See, e.g.,

![h2_frac_func_stellar_mass](https://user-images.githubusercontent.com/20153933/109433192-69058680-7a0f-11eb-9923-e2bcfbdea5ae.png)

2021-03-01 19:15 UTC, wmfw23 commented on data/GalaxyHItoStellarFractionMetallicity/convertDeLooze20.py
> +# find all the sub headers in the file (tthey contain a ':')
this file doesn't actually do anything and was added by mistake as a copy of an already accepted data script, so have removed and modified and added the correct file

2021-03-01 19:16 UTC, wmfw23 commented on data/GalaxyColdGasFractions/conversion/convertCatinella2018.py
> +import itertools as it
this isn't relevant anymore as don't include the colours in the raw file, so simplified it.

2021-03-01 19:17 UTC, wmfw23 commented on data/GalaxyColdGasFractions/conversion/convertCatinella2018.py
> +ORIGINAL_H = 0.7
this isn't relevant anymore as don't include the colours in the raw file, so simplified it.

2021-03-02 12:56 UTC, EvgeniiChaikin commented on data/GalaxyColdGasFractions/conversion/convertCatinella2018.py
> +ORIGINAL_H = 0.7
Thanks!

2021-03-02 13:25 UTC, EvgeniiChaikin commented
Hi @wmfw23,

I have had a brief second look at the changes. 

Just a few tiny remaining comments, and then the branch can be merged:

- There are still a few places in the code where you are using `comoving=0` instead of `comoving=True/False ` and `scatter=array with zeros` instead of `scatter=None`
-  I don't understand why in `convertDeLooze20.py` you define `inc=0` and increment it by one by hand at the end of each iteration (`enumerate` is doing it for you anyway)
- Can you please add the same comment "_From cosmology assumed by Catinella+18_" to `convertCatinellaSaintongeComposite.py`?

2021-03-02 15:59 UTC, EvgeniiChaikin approved these changes

2021-03-02 16:01 UTC, EvgeniiChaikin commented
Thank you @wmfw23! I think this all looks very good now!

@JBorrow if you were not planning to have a final look, I am ready to merge it.

2021-03-03 08:53 UTC, JBorrow commented on data/GalaxyHItoStellarFractionMetallicity/conversion/convertDeLooze20.py
>  inc = 0
`inc` doesn't need to be initialised here

2021-03-03 08:53 UTC, JBorrow commented
Other than my one nit pick we're good to go.

2021-03-05 09:18 UTC, merged